#!/usr/bin/env bash
# Tier 2 — run the POSIX kit with a REAL PHP interpreter as the backend.
#
# The shim spawns its backend with **zero arguments** via execv(), so the backend
# must be directly executable. A PHP file whose first line is a shebang works:
# the kernel (or Cygwin's exec) runs the interpreter with the script path
# appended, and PHP's CLI SAPI skips the shebang line. That is how a "script" can
# stand in for the aot-compiled `app.exe`.
#
# Two path gotchas, both learned the hard way on Cygwin:
#  * TYPEPHP_APP is passed to PHP as the *script argument*. A Windows PHP cannot
#    open a `/cygdrive/...` path, so hand it a Windows-style path (`cygpath -m`).
#    The shim's own execv() accepts either form.
#  * `require` inside the generated wrapper must use an absolute path. `__DIR__`
#    would hand Windows PHP a Cygwin path it cannot resolve.
#
# Usage:
#   ./tier2.sh                                  # auto-detects a PHP >= 8.0
#   PHP_EXE=/d/cygwin64/bin/php.exe ./tier2.sh   # explicit (7.4 -> refused)
#   N_CALLS=20 ./tier2.sh
# Exit: whatever run.sh returns.
set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
. "$HERE/resolve-root.sh"
typephp_locate "$HERE"
typephp_default_work "$HERE"
PHP_EXE="${PHP_EXE:-}"

# Auto-detect when the caller did not name an interpreter. Cygwin's own PHP is
# 7.4 (too old for backend.php), and the tpc distro ships an 8.x one, so a bare
# `./tier2.sh` otherwise dies on a missing env var that it could have filled in
# itself. Only candidates that actually report >= 8.0 are accepted.
if [ -z "$PHP_EXE" ]; then
  for cand in \
    "php" \
    "/cygdrive/d/git/php/tpc_v0.9.3_windows_x64/php.exe" \
    "/cygdrive/c/php/php.exe" \
    "/usr/bin/php"; do
    p="$(command -v "$cand" 2>/dev/null)" || p="$cand"
    [ -x "$p" ] || continue
    v="$("$p" -r 'echo PHP_VERSION_ID;' 2>/dev/null || echo 0)"
    if [ "${v:-0}" -ge 80000 ] 2>/dev/null; then PHP_EXE="$p"; break; fi
  done
fi
if [ -z "$PHP_EXE" ]; then
  echo "set PHP_EXE to a PHP >= 8.0 binary"
  echo "  (backend.php uses str_starts_with/str_contains, so 7.x will not do)"
  echo "  auto-detection tried: php, the tpc distro, C:/php/php.exe, /usr/bin/php"
  exit 2
fi
if ! command -v "$PHP_EXE" >/dev/null 2>&1 && [ ! -x "$PHP_EXE" ]; then
  echo "PHP_EXE is not executable: $PHP_EXE"; exit 2
fi
BACKEND_PHP="${BACKEND_PHP:-$TP_BACKEND_DEF}"
if [ ! -f "$BACKEND_PHP" ]; then
  # This kit is shipped standalone (the skill bundles it next to its own
  # backend_shell.cpp), so the resolved default is not a guarantee — the
  # backend under test is the user's. Point at it explicitly instead of
  # failing with a path they did not choose.
  echo "backend not found: $BACKEND_PHP"
  if [ -n "$TP_ROOT" ]; then
    echo "  resolved from the repo root: $TP_ROOT/src/backend.php"
  else
    echo "  standalone kit: defaults to ../backend.php (next to backend_shell.cpp)"
  fi
  echo "  point it at your own backend instead:"
  echo "    BACKEND_PHP=/path/to/backend.php ./tier2.sh"
  exit 2
fi

# backend.php needs PHP 8; fail loudly instead of debugging a syntax error
# inside the pump later.
vid="$("$PHP_EXE" -r 'echo PHP_VERSION_ID;' 2>/dev/null || echo 0)"
if [ "${vid:-0}" -lt 80000 ] 2>/dev/null; then
  echo "PHP_EXE reports PHP_VERSION_ID=$vid; backend.php needs >= 80000 (PHP 8.0)"
  echo "  a Cygwin PHP 7.4 is common — use the tpc distro's php.exe instead"
  exit 2
fi
echo "PHP backend interpreter: $PHP_EXE (PHP_VERSION_ID=$vid)"

# Wrap in the caller's scratch dir, not the source tree: the earlier version
# hardcoded $HERE/.work and so wrote into the kit directory even when WORK was
# overridden (and left a stray .work/ behind in a checkout).
#
# Exported on purpose: run.sh is invoked below and would otherwise resolve a
# *different* default (a fresh temp dir in the standalone home), leaving the
# wrapper in a directory nobody prints and nobody cleans up.
WORK="${WORK:-$TP_WORK}"
export WORK
WRAPPER="$WORK/tier2_backend.php"
mkdir -p "$WORK"

# Use -m (mixed, forward slashes) so the path is valid for PHP without escaping.
to_php_path() {
  if command -v cygpath >/dev/null 2>&1; then cygpath -m "$1"; else printf '%s' "$1"; fi
}
PHP_EXE_M="$(to_php_path "$PHP_EXE")"
BACKEND_M="$(to_php_path "$BACKEND_PHP")"
WRAPPER_M="$(to_php_path "$WRAPPER")"

{
  printf '#!%s\n' "$PHP_EXE_M"
  printf '<?php\n'
  printf '// generated by posix-test/tier2.sh — stock PHP needs an explicit main();\n'
  printf '// the aot compiler calls it automatically, so backend.php stays pure.\n'
  printf 'require %s;\n' "$(printf "'%s'" "$BACKEND_M")"
  printf 'main();\n'
} >"$WRAPPER"
chmod +x "$WRAPPER"

echo "wrapper: $WRAPPER"
echo "          (shebang -> $PHP_EXE_M)"
BACKEND_APP="$WRAPPER_M" bash "$HERE/run.sh"
