#!/usr/bin/env bash
# Verify the SHIPPING path of the cross-platform shim on POSIX: `--launch` mode.
#
# Why this is separate from run.sh
# -------------------------------
# In dev mode the launcher is the parent and spawns the shim. In **packaged** mode
# the roles invert: the shim IS the app entry (`<name>.exe`, argc==1), so it
#   1. reads `<exe_dir>/<exe_stem>.conf`,
#   2. creates the AF_UNIX endpoint itself,
#   3. spawns the PHP backend with inherited stdio, and
#   4. spawns the STOCK launcher as its client, in the upstream direction:
#        launcher <html> <endpoint> [title] [WxH] [version]
# That is the path a Linux user would actually run — and it had never been
# exercised on POSIX. `launcher-linux` needs GTK + webkit2gtk, so the C mock
# launcher stands in, accepting the identical argv layout via
# MOCK_LAUNCHER_ARGV=launcher. (Its stdout is /dev/null in this mode — the shim
# spawns the launcher with no stdio, the POSIX peer of bInheritHandles=FALSE — so
# it reports the arguments it received as a FRAME, which the shim logs.)
#
# So this adds what run.sh cannot cover: conf parsing, `app=`/`launcher=`
# resolution against the exe directory, the argv ORDER given to the launcher, the
# no-stdio spawn, and a teardown that must not orphan the launcher.
#
# Usage: ./launch-mode.sh          Exit: 0 = pass, 1 = fail, 2 = unusable host.
set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
SRC="$HERE/../backend_shell.cpp"
WORK="${WORK:-$HERE/.work}/launch"
N_CALLS="${N_CALLS:-6}"
APP_NAME="${APP_NAME:-posixshim}"
TITLE="POSIX Launch Test"
SIZE="800x600"
VER="0.0.1"

pass=0; fail=0
ok()  { echo "  [PASS] $*"; pass=$((pass + 1)); }
bad() { echo "  [FAIL] $*"; fail=$((fail + 1)); }

# Same host guard as run.sh (and it must come first, for the same reason).
case "$(uname -s)" in
  Linux | Darwin | CYGWIN*) ;;
  *)
    echo "This kit verifies the POSIX branch, but this host is $(uname -s)."
    echo "Run it on Linux/macOS, or under Cygwin's bash."
    exit 2 ;;
esac
command -v g++ >/dev/null 2>&1 || { echo "g++ not found"; exit 2; }

echo "======================================================================"
echo " POSIX packaged-entry (--launch) verification   @ $(uname -s)"
echo "======================================================================"

# ------------------------------------------------------------------ build ---
echo "== [1/4] build both binaries =="
mkdir -p "$WORK"
if g++ -std=c++17 -O2 -Wall -Wextra -o "$WORK/$APP_NAME" "$SRC" 2>"$WORK/build.log"; then
  ok "shim compiled clean (-Wall -Wextra)"
else
  bad "shim compile FAILED"; sed 's/^/     /' "$WORK/build.log"
  echo; echo "RESULT: $pass passed, $fail failed"; exit 1
fi
CC_BIN="${CC:-gcc}"
command -v "$CC_BIN" >/dev/null 2>&1 || CC_BIN="g++ -x c"
# shellcheck disable=SC2086
if $CC_BIN -O2 -Wall -Wextra -o "$WORK/mock_launcher" "$HERE/mock_launcher.c" \
     >"$WORK/cc.log" 2>&1; then
  ok "mock launcher compiled clean"
else
  bad "mock launcher compile FAILED"; sed 's/^/     /' "$WORK/cc.log"
  echo; echo "RESULT: $pass passed, $fail failed"; exit 1
fi
chmod +x "$WORK/$APP_NAME" "$WORK/mock_launcher"

# ------------------------------------------------------------------ stage ---
echo "== [2/4] stage a portable app folder (what a Linux user would unzip) =="
mkdir -p "$WORK/frontend"
printf '<!doctype html><title>posix launch</title>\n' >"$WORK/frontend/index.html"
chmod +x "$HERE/mock_backend.py"
# The entry finds its conf as <exe_dir>/<exe_stem>.conf — same rule as Windows.
cat >"$WORK/$APP_NAME.conf" <<EOF
# generated by launch-mode.sh
html=frontend/index.html
title=$TITLE
size=$SIZE
version=$VER
app=$HERE/mock_backend.py
launcher=$WORK/mock_launcher
EOF
ok "staged $WORK/$APP_NAME.conf (+ frontend/)"
sed 's/^/       /' "$WORK/$APP_NAME.conf"

# ------------------------------------------------------------------- run ----
echo "== [3/4] run the entry with NO arguments (argc==1 => launch mode) =="
rm -f "$WORK/shim.log" "$WORK/app.sock" "$WORK/entry.out"
( cd "$WORK" && MOCK_LAUNCHER_ARGV=launcher N_CALLS="$N_CALLS" \
    TYPEPHP_SHELL_LOG="$WORK/shim.log" "./$APP_NAME" >"$WORK/entry.out" 2>&1 ) &
ENTRY_PID=$!

# The mock launcher closes its end when done, so the entry must finish by itself.
done_at=0
for _ in $(seq 1 300); do          # up to 30s
  kill -0 "$ENTRY_PID" 2>/dev/null || { done_at=1; break; }
  sleep 0.1
done
if [ "$done_at" -eq 1 ]; then
  wait "$ENTRY_PID"; rc=$?
  [ "$rc" -eq 0 ] && ok "entry exited 0 on its own" || bad "entry exit code $rc"
else
  bad "entry still running after the client closed (teardown stuck)"
  kill "$ENTRY_PID" 2>/dev/null
fi

SLOG="$WORK/shim.log"
[ -f "$SLOG" ] || { bad "no shim log at $SLOG — did the conf resolve?"; }

# ------------------------------------------------------------------ assert --
echo "== [4/4] assertions (all evidence comes from the entry's own log) =="
grep -q "spawned launcher" "$SLOG" 2>/dev/null \
  && ok "spawned the launcher (conf launcher= resolved)" \
  || bad "never spawned the launcher"
grep -q "launcher connected" "$SLOG" 2>/dev/null \
  && ok "launcher connected over AF_UNIX" \
  || bad "launcher never connected"
grep -q "transport=unix-socket" "$SLOG" 2>/dev/null \
  && ok "endpoint created by the entry (transport=unix-socket)" \
  || bad "no AF_UNIX endpoint"

# conf -> argv: the launcher echoes back what it was handed.
want="SYS launch-argv html=$WORK/frontend/index.html title=$TITLE size=$SIZE ver=$VER"
if grep -qF "$want" "$SLOG" 2>/dev/null; then
  ok "conf parsed and handed to the launcher in the right order"
elif grep -q "SYS launch-argv" "$SLOG" 2>/dev/null; then
  bad "launch argv mismatch"
  echo "       want: $want"
  grep "SYS launch-argv" "$SLOG" | sed 's/^/       got:  /'
else
  bad "the launcher never reported its argv (conf/html wrong?)"
fi

f_call="$(grep -c 'L->P: CALL' "$SLOG" 2>/dev/null || true)"; f_call="${f_call:-0}"
f_ret="$(grep -c 'P->L: RET' "$SLOG" 2>/dev/null || true)";  f_ret="${f_ret:-0}"
if [ "$f_call" = "$N_CALLS" ] && [ "$f_ret" = "$N_CALLS" ]; then
  ok "pump round-tripped $f_call CALL / $f_ret RET"
else
  bad "expected $N_CALLS CALL and $N_CALLS RET, got $f_call / $f_ret"
fi

grep -q "launcher closed" "$SLOG" 2>/dev/null \
  && ok "entry noticed the launcher going away" \
  || bad "entry never logged 'launcher closed'"
if [ -e "$WORK/app.sock" ]; then
  bad "socket file left behind: $WORK/app.sock"
else
  ok "socket file unlinked on exit"
fi

# --- orphan check, WITH a positive control -----------------------------------
# Two traps here, both hit while writing this:
#  * Cygwin's `ps -ef` prints the RESOLVED ABSOLUTE PATH of the binary, and
#    ignores argv[0] (so `exec -a` tricks do not fool it, but neither does
#    grepping for the relative invocation form). Match on the binary NAMES.
#  * A negative assertion with no positive control is worthless: the first
#    version of this check "passed" simply because nothing was running. So start
#    a known-live process under a matching name, prove the matcher SEES it, then
#    prove it disappears — only then trust the zero.
count_staged() {
  ps -ef 2>/dev/null | grep -E 'mock_launcher|posixshim' | grep -v grep | wc -l | tr -d ' '
}
cp /usr/bin/sleep "$WORK/mock_launcher_probe" 2>/dev/null || \
  cp "$(command -v sleep)" "$WORK/mock_launcher_probe"
"$WORK/mock_launcher_probe" 20 >/dev/null 2>&1 &
CTRL=$!
sleep 1
if [ "$(count_staged)" -ge 1 ]; then
  ok "orphan check has a working positive control (it sees a live process)"
else
  bad "orphan check can never fail — it cannot see even a live process; fix it"
fi
kill "$CTRL" 2>/dev/null; wait "$CTRL" 2>/dev/null
rm -f "$WORK/mock_launcher_probe"
sleep 0.5
leftover="$(count_staged)"
if [ "$leftover" -eq 0 ]; then
  ok "no orphaned launcher/entry processes"
else
  bad "$leftover process(es) still running from this kit"
  ps -ef 2>/dev/null | grep -E 'mock_launcher|posixshim' | grep -v grep | sed 's/^/       /'
fi

echo
echo "----------------------------------------------------------------------"
echo "frames: CALL=$f_call RET=$f_ret"
echo "log: $SLOG"
echo "RESULT: $pass passed, $fail failed"
[ "$fail" -eq 0 ] || exit 1
echo "PACKAGED-ENTRY (LAUNCH) MODE OK"
